### ISSUE TITLE
`Error::PeerIdMismatch` is sometimes reported as `Error::Other` when WebSocket transport is used

### ISSUE THREAD

**Issue by dmitry-markin** [paritytech/litep2p#67]
When dialing a peer using invalid peer id over WebSocket transport, the error is sometimes reported as [`Error::Other`](https://github.com/paritytech/litep2p/blob/fd0bdfb1e831061d7ec2fa55746ff8e891ad0ff8/src/error.rs#L72-L73) instead of [`Error::PeerIdMismatch`](https://github.com/paritytech/litep2p/blob/fd0bdfb1e831061d7ec2fa55746ff8e891ad0ff8/src/error.rs#L114-L115). The error string reported is `Cannot assign requested address (os error 99)`.

This is possible to reproduce using https://github.com/dmitry-markin/p2p-probe and passing a multiaddress of a node with `/ws` protocol.

This has never happened over TCP transport.

**Comment by altonen** [comment]
Did you happened to dial the node a second time in close succession? I recently ran into `EADDRNOTAVAIL` (the same error you got) because connection got closed and then I tried to dial the same peer soon after. Because of port reuse and `TIME_WAIT`, the socket pair is "in use" and cannot be used until the socket has fully closed. Shouldn't happen if port reuse is not enabled but litep2p doesn't allow disabling port reuse. This happened with TCP, not with WS. There could be an additional problem with WS but redialing after the connection was just closed will cause the dial to fail which is kind of annoying.

Would be nice if port reuse could be enabled/disabled in TCP/WS config. Should be a trivial change and wouldn't cause API breakage in Polkadot SDK. Something you'd be willing to consider?

**Comment by dmitry-markin** [comment]
You are right, this happens when I dial a node a second time in close succession. I also suspected port reuse, but ruled it out because the tests (incorrectly) showed the error was happening on the first dial.

Let's add a port reuse toggle to the config. Shouldn't it be enough to add it to TCP config, as WS reuses the TCP transport?

**Comment by altonen** [comment]
WS and TCP share no code in litep2p, unlike in rust-libp2p. There was a plan to reduce duplicate code between the transports but never time to actually do it.

**Comment by dmitry-markin** [comment]
I know why I never had this error with TCP: I passed empty `listen_addresses` to TCP config, but didn't change the WS's default. Passing empty `listen_addresses` to WS fixed the issue.

I'm going to expose `reuse_port` in TCP & WS configs in litep2p anyway.

**Comment by dmitry-markin** [comment]
> I'm going to expose `reuse_port` in TCP & WS configs in litep2p anyway.

Done in https://github.com/paritytech/litep2p/pull/69.

**Comment by altonen** [comment]
> I know why I never had this error with TCP: I passed empty `listen_addresses` to TCP config, but didn't change the WS's default. Passing empty `listen_addresses` to WS fixed the issue.
> 
> I'm going to expose `reuse_port` in TCP & WS configs in litep2p anyway.

It's weird that you haven't run into it but I guess there's an element of chance at play. On Linux it seemed to work better with port reuse enabled but when I tried running a node on macOS, it was almost completely unusable. Granted it was a tiny local network of nodes all connected to each other and hitting a corner case where the node is dialed just after the connection got closed. Disabling port reused fixed it.
